### ISSUE TITLE
Mapper.xml 定位错误

### ISSUE THREAD

**Issue by xtuer** [zhaoqin102/mybatis-support#6]
版本: 1.8。
现象: 当 IDEA 编译后，如果生成 out 目录并把资源 (xml mapper 文件) 等都复制到 out 目下时，在 Java interface 的 Mapper 里点击跳转到 xml mapper 文件时，打开的是 out 目录下的 xml mapper 文件，而不是源码 resources 下的 xml mapper 文件。

1.8 版本以前没有这个问题。

**Comment by zhaoqin102** [comment]
我看看  我没试过复制到out目录

**Comment by zhaoqin102** [comment]
我试了下,  生成out目录以后,  在Mapper里面点击跳转还是跳转到了source里面的xml文件,  是不是你的out也配置成source了

**Comment by xtuer** [comment]
> 我试了下, 生成out目录以后, 在Mapper里面点击跳转还是跳转到了source里面的xml文件, 是不是你的out也配置成source了

有可能当时升级后是老的项目，现在 gradle 项目编译的都生成到 build 目录，没有 out 了，目前跳转是正常的。
